<script lang="ts">
  import '../app.css';
  import ErrorBoundary from '$lib/components/ErrorBoundary.svelte';
</script>

<svelte:head>
  <title>Create SvelteKit App</title>
  <meta name="description" content="Generated by create-svelte" />
</svelte:head>

<div class="flex min-h-screen flex-col bg-gray-50">
  <ErrorBoundary>
    <slot />
  </ErrorBoundary>
</div>

<style>
  :global(body) {
    margin: 0;
    padding: 0;
  }
</style>
